version: '3.8'

services:
  db:
    image: docker.io/library/postgres:16-alpine
    container_name: myotel-postgres
    environment:
      POSTGRES_DB: myoteldb
      POSTGRES_USER: myoteluser
      POSTGRES_PASSWORD: myotelpass123
    ports:
      - "0.0.0.0:5432:5432"
      # Migration runner - only needed when automatic migrations fail
  migrations:
    build:
      context: .
      dockerfile: Dockerfile.migrations
    container_name: myotel-migrations
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=myoteldb;Username=myoteluser;Password=myotelpass123;
    depends_on:
      - db
    networks:
      - myotel-network
    profiles:
      - migrations

volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - myotel-network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: myotel-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:8080
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=myoteldb;Username=myoteluser;Password=myotelpass123;
      - OpenTelemetry__ServiceName=MyOpenTelemetryApi
      - OpenTelemetry__ServiceVersion=1.0.0-container
      - OpenTelemetry__Exporter__Console__Enabled=true
      - OpenTelemetry__Exporter__File__Enabled=true
      - OpenTelemetry__Exporter__File__LogPath=/app/logs/otel-logs.json
      - OpenTelemetry__Exporter__OTLP__Enabled=false
      - OpenTelemetry__Sampling__AlwaysOn=true
    ports:
      - "0.0.0.0:5174:8080"
    depends_on:
      - db
    volumes:
      - ./logs:/app/logs
    networks:
      - myotel-network

volumes:
  postgres_data:
    driver: local

networks:
  myotel-network:
    driver: bridge